### ISSUE TITLE
Is it possible to load a PDF in the viewer?

### ISSUE THREAD

**Issue by steveharan** [igorlino/fancybox-plus#5]
Is it possible to load a PDF in the viewer?

**Comment by igorlino** [comment]
Hi, 

Yes.
You need to provide the right HMTL template. You may use  the advanced options 'content' (see http://igorlino.github.io/fancybox-plus/api.htm )
but there are other alternatives ways.

CSS:

``` css
.native-pdf-holder {
    display: block;
}
```

JS:

``` javascript
<div class="native-pdf-holder">
    <object class="native-pdf-object" data="YOUR_PDF_URL" width="100%"
            height="100%">
        <p>It appears you do not have a PDF plugin for this browser.</p>
    </object>
</div>
```

Replace YOUR_PDF_URL by your actual url.
This code would work with Chrome and IE10, older browsers may need other html

**Comment by igorlino** [comment]
Also, you may use an external viewer ( like https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm?hl=en ) , in case you are using Chrome.

It works pretty nice.
