### ISSUE TITLE
jquery.easing is missing in package

### ISSUE THREAD

**Issue by umbrella-ivan-zhukov** [igorlino/fancybox-plus#6]
Hi, I've plugged fancy box, but getting 404 error, because `bower_components/fancybox-plus/src/jquery.easing-1.3.pack.js` is missing in package.

Can you please include jquery.easing-1.3.pack.js to src/ folder ?

Thanks in advance!

**Comment by kkbrains** [comment]
+1

**Comment by ASDAlexey** [comment]
+1

**Comment by igorlino** [comment]
actually, we should not include 3rd party in that directory, the right way is to declare the dependency via the package manager (bower or/and npm).
